// <auto-generated />
using System;
using DataAccess.Concrete.Entityframework.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(CuboContext))]
    [Migration("20230825093850_OrderPropertyAddProcess")]
    partial class OrderPropertyAddProcess
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Concrete.Kullanici", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("Core.Entities.Concrete.OperationClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OperationClaims");
                });

            modelBuilder.Entity("Core.Entities.Concrete.UserOperationClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OperationId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserOperationClaims");
                });

            modelBuilder.Entity("Entities.Concrete.CctvDamarDizayn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnaId")
                        .HasColumnType("int");

                    b.Property<double>("Ayna")
                        .HasColumnType("float");

                    b.Property<double>("Back")
                        .HasColumnType("float");

                    b.Property<double>("Cap")
                        .HasColumnType("float");

                    b.Property<int>("DamarNo")
                        .HasColumnType("int");

                    b.Property<double>("Etk")
                        .HasColumnType("float");

                    b.Property<double>("Hatve")
                        .HasColumnType("float");

                    b.Property<string>("Imalat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kalip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("KesitCapi")
                        .HasColumnType("float");

                    b.Property<string>("Renk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CctvDamarDizayn");
                });

            modelBuilder.Entity("Entities.Concrete.CctvGenelDizayn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Ayna")
                        .HasColumnType("float");

                    b.Property<double>("Back")
                        .HasColumnType("float");

                    b.Property<string>("Core")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DamarSayisi")
                        .HasColumnType("int");

                    b.Property<string>("Degistiren")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DegistirilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<double>("DisCap")
                        .HasColumnType("float");

                    b.Property<string>("DisKilif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("FolyoOlcusu")
                        .HasColumnType("float");

                    b.Property<string>("FolyoTipi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GirilenDamarSayisi")
                        .HasColumnType("int");

                    b.Property<double>("Hatve")
                        .HasColumnType("float");

                    b.Property<string>("Kablo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kalip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("KesitCapi")
                        .HasColumnType("float");

                    b.Property<double>("Orgu")
                        .HasColumnType("float");

                    b.Property<string>("OrguTelYapisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PolyesterOlcusu")
                        .HasColumnType("float");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Zorlama")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CctvGenelDizayn");
                });

            modelBuilder.Entity("Entities.Concrete.CctvIsEmri", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("BukumBarkodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DamarBarkodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DamarBukumBarkodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Degistiren")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisKilifBarkodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DolguBarkodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FolyoBarkodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KilifBarkodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrguBarkodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CctvIsEmirleri");
                });

            modelBuilder.Entity("Entities.Concrete.KabloUretim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CalismaSuresi")
                        .HasColumnType("float");

                    b.Property<string>("Degistiren")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("GenelAriza")
                        .HasColumnType("float");

                    b.Property<double>("HurdaCu")
                        .HasColumnType("float");

                    b.Property<double>("HurdaPvc")
                        .HasColumnType("float");

                    b.Property<string>("KabloIsmi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("KayipZaman")
                        .HasColumnType("float");

                    b.Property<double>("KesitCapi")
                        .HasColumnType("float");

                    b.Property<double>("Kopma")
                        .HasColumnType("float");

                    b.Property<int>("MakineId")
                        .HasColumnType("int");

                    b.Property<double>("Metraj")
                        .HasColumnType("float");

                    b.Property<double>("RenkDegisimi")
                        .HasColumnType("float");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<double>("Verimlilik")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("KabloUretim");
                });

            modelBuilder.Entity("Entities.Concrete.KesitYapisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Alan")
                        .HasColumnType("float");

                    b.Property<double>("Ayna")
                        .HasColumnType("float");

                    b.Property<double>("Back")
                        .HasColumnType("float");

                    b.Property<double>("Coef")
                        .HasColumnType("float");

                    b.Property<double>("DisCap")
                        .HasColumnType("float");

                    b.Property<double>("Hatve")
                        .HasColumnType("float");

                    b.Property<double>("KesitCapi")
                        .HasColumnType("float");

                    b.Property<double>("KilcalDamarCapi")
                        .HasColumnType("float");

                    b.Property<int>("KilcalDamarSayisi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("KesitYapisi");
                });

            modelBuilder.Entity("Entities.Concrete.Makine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Isinma")
                        .HasColumnType("int");

                    b.Property<int>("KesitDegisimi")
                        .HasColumnType("int");

                    b.Property<int>("Kopma")
                        .HasColumnType("int");

                    b.Property<string>("MakineIsmi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("No")
                        .HasColumnType("int");

                    b.Property<int>("RenkDegisimi")
                        .HasColumnType("int");

                    b.Property<double?>("Verimlilik")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Makineler");
                });

            modelBuilder.Entity("Entities.Concrete.MakineKesitHizTablosu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Hiz")
                        .HasColumnType("int");

                    b.Property<double>("KesitCapi")
                        .HasColumnType("float");

                    b.Property<int>("MakineId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MakineKesitHizTablosu");
                });

            modelBuilder.Entity("Entities.Concrete.OperatorIsEmri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Ayna")
                        .HasColumnType("float");

                    b.Property<double>("Back")
                        .HasColumnType("float");

                    b.Property<string>("Barkod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Degistiren")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DisCap")
                        .HasColumnType("float");

                    b.Property<string>("DizaynTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kalip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("KesitCapi")
                        .HasColumnType("float");

                    b.Property<string>("MakineIsmi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Metraj")
                        .HasColumnType("float");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TamamlanmaDurumu")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<double>("TeorikMaliyet")
                        .HasColumnType("float");

                    b.Property<string>("UrunIsmi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OperatorIsEmirleri");
                });

            modelBuilder.Entity("Entities.Concrete.Process", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsEmriId")
                        .HasColumnType("int");

                    b.Property<string>("Isim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OperatorIsEmriId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<bool>("TamamlanmaDurumu")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("OperatorIsEmriId");

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("Entities.Concrete.Sarfiyat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("HurdaCu")
                        .HasColumnType("float");

                    b.Property<double>("HurdaPvc")
                        .HasColumnType("float");

                    b.Property<int>("KabloId")
                        .HasColumnType("int");

                    b.Property<double>("KesitCapi")
                        .HasColumnType("float");

                    b.Property<double>("KullanilanCu")
                        .HasColumnType("float");

                    b.Property<double>("KullanilanPvc")
                        .HasColumnType("float");

                    b.Property<int>("MakineId")
                        .HasColumnType("int");

                    b.Property<double>("Maliyet")
                        .HasColumnType("float");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Sarfiyat");
                });

            modelBuilder.Entity("Entities.Concrete.SatisPlanlama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Fiyat")
                        .HasColumnType("float");

                    b.Property<double>("Iskonto")
                        .HasColumnType("float");

                    b.Property<string>("KabloIsmi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListeFiyati")
                        .HasColumnType("float");

                    b.Property<int>("Metraj")
                        .HasColumnType("int");

                    b.Property<string>("PaketlemeSekli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<double>("Tonaj")
                        .HasColumnType("float");

                    b.Property<double>("Tutar")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("SatisPlanlama");
                });

            modelBuilder.Entity("Entities.Concrete.TekDamarDizayn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Ayna")
                        .HasColumnType("float");

                    b.Property<double>("Back")
                        .HasColumnType("float");

                    b.Property<string>("Core")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Degistiren")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DegistirilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<double>("DisCap")
                        .HasColumnType("float");

                    b.Property<double>("DisKilif1")
                        .HasColumnType("float");

                    b.Property<double>("DisKilif2")
                        .HasColumnType("float");

                    b.Property<string>("DizaynTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Hatve")
                        .HasColumnType("float");

                    b.Property<string>("KabloIsmi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kalip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("KesitCapi")
                        .HasColumnType("float");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TekDamarDizayn");
                });

            modelBuilder.Entity("Entities.Concrete.TelefonDamarDizayn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnaId")
                        .HasColumnType("int");

                    b.Property<double>("Ayna")
                        .HasColumnType("float");

                    b.Property<double>("Back")
                        .HasColumnType("float");

                    b.Property<double>("Cap")
                        .HasColumnType("float");

                    b.Property<int>("DamarNo")
                        .HasColumnType("int");

                    b.Property<double>("Etk")
                        .HasColumnType("float");

                    b.Property<double>("Hatve")
                        .HasColumnType("float");

                    b.Property<string>("Kalip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("KesitCapi")
                        .HasColumnType("float");

                    b.Property<string>("Renk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TelefonDamarDizayn");
                });

            modelBuilder.Entity("Entities.Concrete.TelefonGenelDizayn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Ayna")
                        .HasColumnType("float");

                    b.Property<double>("Back")
                        .HasColumnType("float");

                    b.Property<int>("DamarSayisi")
                        .HasColumnType("int");

                    b.Property<string>("Degistiren")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DegistirilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<double>("DisCap")
                        .HasColumnType("float");

                    b.Property<string>("DisKilif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("FolyoOlcusu")
                        .HasColumnType("float");

                    b.Property<string>("FolyoTipi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GirilenDamarSayisi")
                        .HasColumnType("int");

                    b.Property<string>("Kablo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kalip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("KesitCapi")
                        .HasColumnType("float");

                    b.Property<double>("Orgu")
                        .HasColumnType("float");

                    b.Property<string>("OrguTelYapisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PolyesterOlcusu")
                        .HasColumnType("float");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Zorlama")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TelefonGenelDizayn");
                });

            modelBuilder.Entity("Entities.Concrete.TelefonIsEmri", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("BukumBarkodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DamarBarkodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DamarBukumBarkodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Degistiren")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisKilifBarkodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DolguBarkodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FolyoBarkodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KilifBarkodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrguBarkodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TelefonIsEmirleri");
                });

            modelBuilder.Entity("Entities.Concrete.YanginDamarDizayn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnaId")
                        .HasColumnType("int");

                    b.Property<double>("Ayna")
                        .HasColumnType("float");

                    b.Property<double>("Back")
                        .HasColumnType("float");

                    b.Property<double>("Cap")
                        .HasColumnType("float");

                    b.Property<int>("DamarNo")
                        .HasColumnType("int");

                    b.Property<double>("Etk")
                        .HasColumnType("float");

                    b.Property<double>("Hatve")
                        .HasColumnType("float");

                    b.Property<string>("Kalip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("KesitCapi")
                        .HasColumnType("float");

                    b.Property<string>("Renk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("YanginDamarDizayn");
                });

            modelBuilder.Entity("Entities.Concrete.YanginGenelDizayn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Ayna")
                        .HasColumnType("float");

                    b.Property<double>("Back")
                        .HasColumnType("float");

                    b.Property<int>("DamarSayisi")
                        .HasColumnType("int");

                    b.Property<string>("Degistiren")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DegistirilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<double>("DisCap")
                        .HasColumnType("float");

                    b.Property<string>("DisKilif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("FolyoOlcusu")
                        .HasColumnType("float");

                    b.Property<string>("FolyoTipi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GirilenDamarSayisi")
                        .HasColumnType("int");

                    b.Property<string>("Kablo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kalip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("KesitCapi")
                        .HasColumnType("float");

                    b.Property<double>("Orgu")
                        .HasColumnType("float");

                    b.Property<string>("OrguTelYapisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PolyesterOlcusu")
                        .HasColumnType("float");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Zorlama")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("YanginGenelDizayn");
                });

            modelBuilder.Entity("Entities.Concrete.YanginIsEmri", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("BukumBarkodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DamarBarkodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DamarBukumBarkodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Degistiren")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisKilifBarkodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DolguBarkodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FolyoBarkodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KilifBarkodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrguBarkodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("YanginIsEmirleri");
                });

            modelBuilder.Entity("Entities.Concrete.Process", b =>
                {
                    b.HasOne("Entities.Concrete.OperatorIsEmri", "OperatorIsEmri")
                        .WithMany("Surecler")
                        .HasForeignKey("OperatorIsEmriId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("OperatorIsEmri");
                });

            modelBuilder.Entity("Entities.Concrete.OperatorIsEmri", b =>
                {
                    b.Navigation("Surecler");
                });
#pragma warning restore 612, 618
        }
    }
}
